### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by bbreton09** [supermat/SmartPlug#1]
Bonjour, il me semble que dans le dossier "QueLSS" il manque un fichier jquery-1.11.1.js dans un sous dossier "js" pour que cela fonctionne.

En tout cas super boulot que ça soit le code ou le wiki c'est vraiment pratique merci.

**Comment by FaNiZ-08** [comment]
C'est exact, je n'ai pas inclus jQuery qui peut être téléchargé à l'adresse suivante : http://code.jquery.com/jquery-1.11.1.js
(vu que c'est de l'open source, il ne m'a pas semblé utile ni pertinent de le poser sur GitHub)

Chez moi, il est dans un répertoire annexe, mais il peut être placé dans le même répertoire en remplaçant  :
    &lt;script type="text/javascript" src="../js/jquery-1.11.1.js"&gt;&lt;/script&gt;
par 
    &lt;script type="text/javascript" src="jquery-1.11.1.js"&gt;&lt;/script&gt;
dans master_plug.html (ligne 8)
